### ISSUE TITLE
TypeError: Cannot read property 'useContext' of null

### ISSUE THREAD

**Issue by FreePhoenix888** [deep-foundation/nextjs#26]
# Error
TypeError: Cannot read property 'useContext' of null

# Stack
```
Server Error
TypeError: Cannot read property 'useContext' of null

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
Object.useContext
file:///home/freephoenix888/Programming/dev/node_modules/react/cjs/react.development.js (1618:21)
Object.useRouter
file:///home/freephoenix888/Programming/dev/node_modules/next/dist/client/router.js (120:35)
exports.QueryStoreProvider
file:///home/freephoenix888/Programming/dev/node_modules/@deep-foundation/store/query.js (38:29)
processChild
file:///home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js (3353:14)
resolve
file:///home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js (3270:5)
ReactDOMServerRenderer.render
file:///home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js (3753:22)
ReactDOMServerRenderer.read
file:///home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js (3690:29)
Object.renderToString
file:///home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js (4298:27)
Object.renderPage
file:///home/freephoenix888/Programming/dev/packages/nextjs/node_modules/next/dist/server/render.js (680:46)
Object.defaultGetInitialProps
file:///home/freephoenix888/Programming/dev/packages/nextjs/node_modules/next/dist/server/render.js (350:67)
```

# How to reproduce
```
npm run dev
```

# Server terminal
```
freephoenix888@freephoenix888:~/Programming/dev/packages/nextjs$ npm run dev

> @deep-foundation/nextjs@0.0.0 dev
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - Invalid next.config.js options detected: 
  - The root value has an unexpected property, strictMode, which is not in the list of allowed properties (amp, analyticsId, assetPrefix, basePath, cleanDistDir, compiler, compress, crossOrigin, devIndicators, distDir, env, eslint, excludeDefaultMomentLocales, experimental, exportPathMap, future, generateBuildId, generateEtags, headers, httpAgentOptions, i18n, images, onDemandEntries, optimizeFonts, output, outputFileTracing, pageExtensions, poweredByHeader, productionBrowserSourceMaps, publicRuntimeConfig, reactStrictMode, redirects, rewrites, sassOptions, serverRuntimeConfig, staticPageGenerationTimeout, swcMinify, trailingSlash, typescript, useFileSystemPublicRoutes, webpack).

See more info here: https://nextjs.org/docs/messages/invalid-next-config
event - compiled client and server successfully in 1699 ms (160 modules)
wait  - compiling / (client and server)...
event - compiled client and server successfully in 2.2s (1248 modules)
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
wait  - compiling /_error (client and server)...
error - TypeError: Cannot read property 'useContext' of null
    at Object.useContext (/home/freephoenix888/Programming/dev/node_modules/react/cjs/react.development.js:1618:21)
    at Object.useRouter (/home/freephoenix888/Programming/dev/node_modules/next/dist/client/router.js:120:35)
    at exports.QueryStoreProvider (/home/freephoenix888/Programming/dev/node_modules/@deep-foundation/store/query.js:38:29)
    at processChild (/home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3353:14)
    at resolve (/home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3270:5)
    at ReactDOMServerRenderer.render (/home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3753:22)
    at ReactDOMServerRenderer.read (/home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:3690:29)
    at Object.renderToString (/home/freephoenix888/Programming/dev/packages/nextjs/node_modules/react-dom/cjs/react-dom-server.node.development.js:4298:27)
    at Object.renderPage (/home/freephoenix888/Programming/dev/packages/nextjs/node_modules/next/dist/server/render.js:680:46)
    at Object.defaultGetInitialProps (/home/freephoenix888/Programming/dev/packages/nextjs/node_modules/next/dist/server/render.js:350:67) {
  page: '/'
}
event - compiled client and server successfully in 184 ms (1249 modules)
```

**Comment by FreePhoenix888** [comment]
The latest version of store is installed
```
freephoenix888@freephoenix888:~/Programming/dev/packages/nextjs$ npm ls @deep-foundation/store
@deep-foundation/nextjs@0.0.0 /home/freephoenix888/Programming/dev/packages/nextjs
└─┬ @deep-foundation/deeplinks@0.0.98
  └── @deep-foundation/store@0.0.9
```

**Comment by FreePhoenix888** [comment]
https://github.com/deep-foundation/nextjs/pull/27
